#!/bin/bash

TOOL_HOME=$(cd `dirname "$0"` && pwd -P)
STRIKETOOL_CLI_JVM_OPTS=${STRIKETOOL_CLI_JVM_OPTS:-}
STRIKETOOL_CLI_OPTS=${STRIKETOOL_CLI_OPTS:-}

LIB_DIR=${TOOL_HOME}/lib
TARGET_DIR=${TOOL_HOME}/cli/target/

if [ -f "${LIB_DIR}/striketool-cli.jar" ]; then
  JAR=${LIB_DIR}/striketool-cli.jar
elif [ -f "${TARGET_DIR}/striketool-cli.jar" ]; then
  JAR=${TARGET_DIR}/striketool-cli.jar
else
  echo "Jar striketool-cli.jar not found."
  exit 1
fi

java ${STRIKETOOL_CLI_JVM_OPTS} -jar ${JAR} ${STRIKETOOL_CLI_OPTS} "$@"
